services:
  web:
    build: .

    volumes:
      - .:/app
      - /app/.venv
      - /app/staticfiles
      - sqlite_data:/app/data
    ports:
      - "1759:1759"
    environment:
      UV_PROJECT_ENVIRONMENT: /venv
      ALLOWED_HOSTS: "localhost,127.0.0.1,.nyagah.me"

volumes:
  sqlite_data:
